/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    profile: Profile;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Les projets affichés sur l’accueil, dans l’ordre du champ « Position ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Générée depuis le titre. Ex. « netis-group » → /projets/netis-group/
   */
  slug?: string | null;
  /**
   * 1 = premier projet affiché.
   */
  order: number;
  tone?: ('accent' | 'ink' | 'sand') | null;
  client?: string | null;
  /**
   * Ex. 2024 – 2026
   */
  year?: string | null;
  /**
   * Une phrase, affichée dans la liste et en haut de la page projet.
   */
  tagline?: string | null;
  role?: string | null;
  /**
   * La première est affichée dans la liste de l’accueil.
   */
  expertises?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  cover?: (number | null) | Media;
  /**
   * Si vide : description de l’image dans la médiathèque.
   */
  coverAlt?: string | null;
  /**
   * Affichée en 4 chapitres sous la couverture : Le défi → La stratégie → Réalisations → Impact. Un chapitre vide est masqué.
   */
  caseStudy?: {
    challenge?: string | null;
    strategy?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    deliverables?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Idéalement chiffré : abonnés gagnés, participants, portée…
     */
    impact?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Titres, paragraphes, listes. Bouton « + » ou « / » : insérer une image/vidéo de la médiathèque ou une vidéo YouTube entre deux paragraphes.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        media: number | Media;
        caption?: string | null;
        wide?: boolean | null;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images (JPG, PNG, WebP…), vidéos MP4/WebM et PDF (CV). Stockées dans MinIO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Pour les images : ce que l’on voit (lu par les lecteurs d’écran).
   */
  alt?: string | null;
  caption?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  tone?: T;
  client?: T;
  year?: T;
  tagline?: T;
  role?: T;
  expertises?:
    | T
    | {
        label?: T;
        id?: T;
      };
  cover?: T;
  coverAlt?: T;
  caseStudy?:
    | T
    | {
        challenge?: T;
        strategy?:
          | T
          | {
              text?: T;
              id?: T;
            };
        deliverables?:
          | T
          | {
              text?: T;
              id?: T;
            };
        impact?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  content?: T;
  gallery?:
    | T
    | {
        media?: T;
        caption?: T;
        wide?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Infos générales : hero, À propos, contact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number;
  firstName: string;
  lastName: string;
  location?: string | null;
  role?: string | null;
  /**
   * Alterner des blocs « Texte » et « Mot en gras ». Les espaces et la ponctuation sont dans les blocs Texte.
   */
  intro?:
    | (
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            label: string;
            /**
             * Sinon, la note ci-dessous s’affiche sur une carte bordeaux.
             */
            image?: (number | null) | Media;
            note?: string | null;
            tilt?: ('l' | 'r') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'word';
          }
      )[]
    | null;
  /**
   * Ex. « En recherche d’alternance / stage — Paris ». Laisser vide pour masquer la pastille.
   */
  availability?: string | null;
  heroPhoto?: (number | null) | Media;
  marquee?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  portrait?: (number | null) | Media;
  status?: string | null;
  about?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Affichée en grand, en italique, sous les paragraphes.
   */
  drive?: string | null;
  expertises?:
    | {
        label: string;
        title: string;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  tools?:
    | {
        label: string;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Uniquement de vrais retours (manager, client, partenaire). Section masquée si vide.
   */
  testimonials?:
    | {
        quote: string;
        author: string;
        context?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sous « Parlons-en. ».
   */
  contactLead?: string | null;
  email?: string | null;
  /**
   * Affiche les boutons « Télécharger mon CV » (pied de page et menu).
   */
  cv?: (number | null) | Media;
  phone?: string | null;
  linkedin?: string | null;
  instagram?: string | null;
  instagramLabel?: string | null;
  /**
   * Affichée quand on partage le lien (LinkedIn, WhatsApp…). Par défaut : photo À propos.
   */
  shareImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  location?: T;
  role?: T;
  intro?:
    | T
    | {
        text?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        word?:
          | T
          | {
              label?: T;
              image?: T;
              note?: T;
              tilt?: T;
              id?: T;
              blockName?: T;
            };
      };
  availability?: T;
  heroPhoto?: T;
  marquee?:
    | T
    | {
        label?: T;
        id?: T;
      };
  portrait?: T;
  status?: T;
  about?:
    | T
    | {
        text?: T;
        id?: T;
      };
  drive?: T;
  expertises?:
    | T
    | {
        label?: T;
        title?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  tools?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  process?:
    | T
    | {
        label?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        context?: T;
        id?: T;
      };
  contactLead?: T;
  email?: T;
  cv?: T;
  phone?: T;
  linkedin?: T;
  instagram?: T;
  instagramLabel?: T;
  shareImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}